using namespace std;
try { }
catch(std::exception &exception) { }